[theme]
primaryColor="#253856"
secondaryBackgroundColor="#e7e8ee"
textColor="#000000"


[client]
# Whether to enable st.cache.
# Default: true
caching = true

[server]
runOnSave = true
maxUploadSize = 500